# Generated by Django 3.2.5 on 2022-05-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgrade', models.CharField(blank=True, max_length=200)),
                ('inquirytime', models.DateTimeField(auto_now_add=True, verbose_name='询盘时间')),
                ('cus_id', models.CharField(blank=True, max_length=200)),
                ('cname', models.CharField(blank=True, max_length=200)),
                ('ccountry', models.CharField(blank=True, max_length=200)),
                ('cfrom', models.CharField(blank=True, max_length=200)),
                ('cemail', models.CharField(blank=True, max_length=200)),
                ('ccompany', models.CharField(blank=True, max_length=200)),
                ('cwebsite', models.CharField(blank=True, max_length=200)),
                ('ctype', models.CharField(blank=True, max_length=200)),
                ('cplateform', models.CharField(blank=True, max_length=200)),
                ('cphone', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeekCus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirytime', models.DateTimeField(auto_now_add=True, verbose_name='询盘时间')),
                ('cus_id', models.CharField(blank=True, max_length=200)),
                ('cname', models.CharField(blank=True, max_length=200)),
                ('ccountry', models.CharField(blank=True, max_length=200)),
                ('cfrom', models.CharField(blank=True, max_length=200)),
                ('cemail', models.CharField(blank=True, max_length=200)),
                ('ccompany', models.CharField(blank=True, max_length=200)),
                ('cwebsite', models.CharField(blank=True, max_length=200)),
                ('ctype', models.CharField(blank=True, max_length=200)),
                ('cgrade', models.CharField(blank=True, max_length=200)),
                ('cplateform', models.CharField(blank=True, max_length=200)),
                ('cphone', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_length', models.CharField(blank=True, max_length=200)),
                ('single_width', models.CharField(blank=True, max_length=200)),
                ('panel_length', models.CharField(blank=True, max_length=200)),
                ('panel_width', models.CharField(blank=True, max_length=200)),
                ('panel_size', models.CharField(blank=True, max_length=200)),
                ('number_up', models.CharField(blank=True, max_length=200)),
                ('average_size', models.CharField(blank=True, max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=200)),
                ('amount_size', models.CharField(blank=True, max_length=200)),
                ('basic_price', models.CharField(blank=True, max_length=200)),
                ('RMB_price', models.CharField(blank=True, max_length=200)),
                ('USD_price', models.CharField(blank=True, max_length=200)),
                ('testing_fee', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('layer', models.CharField(blank=True, max_length=200)),
                ('inner_copper', models.CharField(blank=True, max_length=200)),
                ('finish_copper', models.CharField(blank=True, max_length=200)),
                ('thickness', models.CharField(blank=True, max_length=200)),
                ('solder', models.CharField(blank=True, max_length=200)),
                ('silkscreen', models.CharField(blank=True, max_length=200)),
                ('finish', models.CharField(blank=True, max_length=200)),
                ('addings', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cussystem.maincus')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_length', models.CharField(blank=True, max_length=200)),
                ('single_width', models.CharField(blank=True, max_length=200)),
                ('panel_length', models.CharField(blank=True, max_length=200)),
                ('panel_width', models.CharField(blank=True, max_length=200)),
                ('panel_size', models.CharField(blank=True, max_length=200)),
                ('number_up', models.CharField(blank=True, max_length=200)),
                ('average_size', models.CharField(blank=True, max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=200)),
                ('amount_size', models.CharField(blank=True, max_length=200)),
                ('basic_price', models.CharField(blank=True, max_length=200)),
                ('RMB_price', models.CharField(blank=True, max_length=200)),
                ('USD_price', models.CharField(blank=True, max_length=200)),
                ('testing_fee', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('layer', models.CharField(blank=True, max_length=200)),
                ('inner_copper', models.CharField(blank=True, max_length=200)),
                ('finish_copper', models.CharField(blank=True, max_length=200)),
                ('thickness', models.CharField(blank=True, max_length=200)),
                ('solder', models.CharField(blank=True, max_length=200)),
                ('silkscreen', models.CharField(blank=True, max_length=200)),
                ('finish', models.CharField(blank=True, max_length=200)),
                ('addings', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cussystem.maincus')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cussystem.maincus')),
            ],
        ),
    ]
