# Generated by Django 3.2.5 on 2022-05-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cussystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincus',
            name='corders',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maincus',
            name='cqnumber',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
