# Generated by Django 3.2.5 on 2022-05-18 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cussystem', '0002_auto_20220509_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordertime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotations',
            name='quotetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekcus',
            name='createtime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follows',
            name='content_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maincus',
            name='inquirytime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weekcus',
            name='inquirytime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
