# Generated by Django 3.2.5 on 2022-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cussystem', '0003_auto_20220518_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='part_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
